import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { jsPDF } from 'npm:jspdf@4.0.0';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { reportType, filters, includeCharts } = await req.json();

    const doc = new jsPDF();
    let yPos = 20;

    // Header
    doc.setFontSize(20);
    doc.text('Package Manufacturing Compliance Report', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, yPos);
    doc.text(`Generated by: ${user.full_name}`, 20, yPos + 5);
    yPos += 15;

    if (reportType === 'compliance') {
      const requirements = await base44.entities.ComplianceRequirement.list('-created_date', 500);
      
      let filteredReqs = requirements;
      if (filters?.section) {
        filteredReqs = filteredReqs.filter(r => r.section === filters.section);
      }
      if (filters?.status) {
        filteredReqs = filteredReqs.filter(r => r.status === filters.status);
      }
      if (filters?.priority) {
        filteredReqs = filteredReqs.filter(r => r.priority === filters.priority);
      }

      doc.setFontSize(16);
      doc.setTextColor(0);
      doc.text('Compliance Status Report', 20, yPos);
      yPos += 10;

      // Summary stats
      const total = filteredReqs.length;
      const compliant = filteredReqs.filter(r => r.status === 'compliant').length;
      const inProgress = filteredReqs.filter(r => r.status === 'in_progress').length;
      const nonCompliant = filteredReqs.filter(r => r.status === 'non_compliant').length;

      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.text(`Total Requirements: ${total}`, 20, yPos);
      yPos += 7;
      doc.text(`Compliant: ${compliant} (${Math.round((compliant/total)*100)}%)`, 20, yPos);
      yPos += 7;
      doc.text(`In Progress: ${inProgress}`, 20, yPos);
      yPos += 7;
      doc.text(`Non-Compliant: ${nonCompliant}`, 20, yPos);
      yPos += 15;

      // Requirements list
      doc.setFontSize(14);
      doc.text('Requirements Details', 20, yPos);
      yPos += 10;

      filteredReqs.forEach((req, index) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFontSize(10);
        doc.setFont(undefined, 'bold');
        doc.text(`${req.clause_number} - ${req.clause_title}`, 20, yPos);
        yPos += 5;

        doc.setFont(undefined, 'normal');
        doc.setFontSize(9);
        doc.setTextColor(80);
        doc.text(`Status: ${req.status.replace('_', ' ')} | Priority: ${req.priority}`, 20, yPos);
        yPos += 5;
        
        if (req.description) {
          const lines = doc.splitTextToSize(req.description, 170);
          doc.text(lines.slice(0, 3), 20, yPos);
          yPos += lines.slice(0, 3).length * 4;
        }
        
        yPos += 5;
        doc.setTextColor(0);
      });

    } else if (reportType === 'risk') {
      const risks = await base44.entities.RiskAssessment.list('-created_date', 500);
      
      let filteredRisks = risks;
      if (filters?.hazardType) {
        filteredRisks = filteredRisks.filter(r => r.hazard_type === filters.hazardType);
      }
      if (filters?.riskLevel) {
        filteredRisks = filteredRisks.filter(r => r.risk_level === filters.riskLevel);
      }

      doc.setFontSize(16);
      doc.setTextColor(0);
      doc.text('Risk Assessment Report', 20, yPos);
      yPos += 10;

      // Summary
      const critical = filteredRisks.filter(r => r.risk_level === 'critical').length;
      const high = filteredRisks.filter(r => r.risk_level === 'high').length;
      const medium = filteredRisks.filter(r => r.risk_level === 'medium').length;

      doc.setFontSize(12);
      doc.text(`Total Risks: ${filteredRisks.length}`, 20, yPos);
      yPos += 7;
      doc.text(`Critical: ${critical} | High: ${high} | Medium: ${medium}`, 20, yPos);
      yPos += 15;

      // Risk details
      doc.setFontSize(14);
      doc.text('Risk Details', 20, yPos);
      yPos += 10;

      filteredRisks.forEach(risk => {
        if (yPos > 260) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFontSize(10);
        doc.setFont(undefined, 'bold');
        doc.text(`${risk.hazard_type.toUpperCase()} Hazard`, 20, yPos);
        yPos += 5;

        doc.setFont(undefined, 'normal');
        doc.setFontSize(9);
        const desc = doc.splitTextToSize(risk.hazard_description, 170);
        doc.text(desc.slice(0, 2), 20, yPos);
        yPos += desc.slice(0, 2).length * 4 + 3;

        doc.setTextColor(80);
        doc.text(`Risk Level: ${risk.risk_level} | Likelihood: ${risk.likelihood} | Severity: ${risk.severity}`, 20, yPos);
        yPos += 5;

        if (risk.mitigation_strategy) {
          doc.text('Mitigation:', 20, yPos);
          yPos += 4;
          const mitigation = doc.splitTextToSize(risk.mitigation_strategy, 165);
          doc.text(mitigation.slice(0, 2), 25, yPos);
          yPos += mitigation.slice(0, 2).length * 4;
        }

        yPos += 5;
        doc.setTextColor(0);
      });

    } else if (reportType === 'activity') {
      const activities = await base44.entities.ActivityLog.list('-created_date', 500);
      
      let filteredActivities = activities;
      if (filters?.activityType) {
        filteredActivities = filteredActivities.filter(a => a.activity_type === filters.activityType);
      }
      if (filters?.startDate) {
        filteredActivities = filteredActivities.filter(a => 
          new Date(a.created_date) >= new Date(filters.startDate)
        );
      }
      if (filters?.endDate) {
        filteredActivities = filteredActivities.filter(a => 
          new Date(a.created_date) <= new Date(filters.endDate)
        );
      }

      doc.setFontSize(16);
      doc.setTextColor(0);
      doc.text('Activity Log Report', 20, yPos);
      yPos += 10;

      doc.setFontSize(12);
      doc.text(`Total Activities: ${filteredActivities.length}`, 20, yPos);
      yPos += 15;

      doc.setFontSize(14);
      doc.text('Activity Timeline', 20, yPos);
      yPos += 10;

      filteredActivities.forEach(activity => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFontSize(9);
        doc.setFont(undefined, 'bold');
        const date = new Date(activity.created_date).toLocaleString();
        doc.text(date, 20, yPos);
        yPos += 5;

        doc.setFont(undefined, 'normal');
        const desc = doc.splitTextToSize(activity.description, 170);
        doc.text(desc.slice(0, 2), 20, yPos);
        yPos += desc.slice(0, 2).length * 4 + 2;

        doc.setTextColor(80);
        doc.text(`Type: ${activity.activity_type.replace('_', ' ')} | User: ${activity.user_email}`, 20, yPos);
        yPos += 7;
        doc.setTextColor(0);
      });
    }

    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=${reportType}-report-${Date.now()}.pdf`
      }
    });

  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});