import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const body = await req.json();
    const audit = body.data;
    const auditId = body.event?.entity_id;

    if (!audit || !audit.findings?.length) {
      return Response.json({ skipped: true, reason: 'No findings to process' });
    }

    // Only process audits with non_compliant findings
    const criticalFindings = audit.findings.filter(f =>
      f.severity === 'high' || f.severity === 'critical' || f.issue_type === 'Quality Deviation'
    );

    if (criticalFindings.length === 0) {
      return Response.json({ skipped: true, reason: 'No high/critical findings' });
    }

    // Generate CAPA number
    const existingCAPAs = await base44.asServiceRole.entities.CAPA.list('-created_date', 1);
    const lastNum = existingCAPAs.length > 0
      ? parseInt(existingCAPAs[0].capa_number?.split('-').pop() || '0', 10)
      : 0;
    const capaNum = String(lastNum + 1).padStart(3, '0');
    const year = new Date().getFullYear();
    const capaNumber = `CAPA-${year}-${capaNum}`;

    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 30);
    const dueDateStr = dueDate.toISOString().split('T')[0];

    const findingsSummary = criticalFindings
      .map(f => `• [${f.severity?.toUpperCase() || 'HIGH'}] ${f.description || f.issue_type}`)
      .join('\n');

    const capaRecord = await base44.asServiceRole.entities.CAPA.create({
      organization_id: audit.organization_id,
      capa_number: capaNumber,
      title: `CAPA for Audit: ${audit.summary?.substring(0, 80) || auditId}`,
      description: `Auto-generated CAPA from compliance audit findings requiring corrective action.\n\nFindings:\n${findingsSummary}`,
      capa_type: 'corrective',
      source_type: 'compliance_audit',
      source_id: auditId,
      source_reference: audit.summary?.substring(0, 100) || `Audit ID: ${auditId}`,
      status: 'open',
      priority: criticalFindings.some(f => f.severity === 'critical') ? 'critical' : 'high',
      problem_statement: `The following compliance audit findings require corrective action:\n\n${findingsSummary}`,
      due_date: dueDateStr,
      management_signoff_required: true,
      corrective_actions: criticalFindings.map((f, i) => ({
        id: `ca-${i + 1}`,
        action: f.recommendation || `Address finding: ${f.description || f.issue_type}`,
        assigned_to: '',
        due_date: dueDateStr,
        completed: false,
      })),
    });

    // Log activity
    await base44.asServiceRole.entities.ActivityLog.create({
      activity_type: 'system_event',
      entity_type: 'CAPA',
      entity_id: capaRecord.id,
      entity_label: capaNumber,
      description: `CAPA ${capaNumber} auto-created from compliance audit with ${criticalFindings.length} finding(s)`,
      user_email: 'system@automation',
    });

    // Notify admins
    const admins = await base44.asServiceRole.entities.User.filter({ role: 'admin' });
    for (const admin of admins) {
      if (!admin.email) continue;
      await base44.asServiceRole.entities.Notification.create({
        recipient_email: admin.email,
        title: `New CAPA Created: ${capaNumber}`,
        message: `A CAPA has been auto-created from a compliance audit with ${criticalFindings.length} high/critical finding(s). Please review and assign.`,
        type: 'compliance_alert',
        entity_type: 'CAPA',
        entity_id: capaRecord.id,
        priority: 'high',
        is_read: false,
      });
      await base44.asServiceRole.integrations.Core.SendEmail({
        to: admin.email,
        subject: `📋 New CAPA Created: ${capaNumber}`,
        body: `
          <h2>CAPA Automatically Created</h2>
          <p><strong>${capaNumber}</strong> has been created from a compliance audit.</p>
          <h3>Findings Requiring Action:</h3>
          <pre style="background:#f5f5f5;padding:12px;border-radius:4px;">${findingsSummary}</pre>
          <p><strong>Due Date:</strong> ${dueDateStr}</p>
          <p>Please log in to the FSMS Compliance Tracker → CAPA Management to assign and begin the corrective action process.</p>
          <hr/><p><small>Auto-generated by FSMS Compliance System</small></p>
        `,
      });
    }

    return Response.json({
      success: true,
      capa_id: capaRecord.id,
      capa_number: capaNumber,
      findings_processed: criticalFindings.length,
    });

  } catch (error) {
    console.error('createCAPAFromAudit error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});